// THIS FILE IS AUTO-GENERATED by scripts/generate-demo-photos.mjs
// Do not edit manually. Add/remove images in public/assets/demo_pics instead.

export const DEMO_PHOTOS_ARRAY = [
  {
    "url": "/assets/demo_pics/p1.jpg",
    "id": "demo_person_p1"
  },
  {
    "url": "/assets/demo_pics/p2.jpg",
    "id": "demo_person_p2"
  },
  {
    "url": "/assets/demo_pics/p3.jpg",
    "id": "demo_person_p3"
  },
  {
    "url": "/assets/demo_pics/p4.jpg",
    "id": "demo_person_p4"
  }
] as const;

export const DEMO_PHOTO_ID_MAP = new Map<string, string>(
  (DEMO_PHOTOS_ARRAY as readonly { url: string; id: string }[]).map((photo) => [photo.url, photo.id]),
);
